version: 2.1

orbs:
  terraform: circleci/terraform@2.0.1

jobs:
  deploy:
    docker:
      # use next-gen
      - image: cimg/node:12.17.0
    steps:
      - terraform/install:
          arch: amd64
          os: linux
          terraform_version: 0.14.10

workflows:
  main:
    jobs:
      - deploy
